# Generated by Django 2.1.7 on 2019-03-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacted_archiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactedsitelogentry',
            name='action',
            field=models.CharField(choices=[('artist_merge', 'artist_merge'), ('artist_delete', 'artist_delete'), ('group_rename', 'group_rename'), ('group_add_artist', 'group_add_artist'), ('group_remove_artist', 'group_remove_artist'), ('group_automatic_delete', 'group_automatic_delete'), ('torrent_upload', 'torrent_upload'), ('torrent_edit', 'torrent_edit'), ('torrent_delete', 'torrent_delete'), ('torrent_inactivity_delete', 'torrent_inactivity_delete'), ('request_created', 'request_created'), ('request_filled', 'request_filled'), ('request_unfilled', 'request_unfilled'), ('collage_created', 'collage_created'), ('collage_deleted', 'collage_deleted')], max_length=64, null=True),
        ),
    ]
