# Generated by Django 2.1.7 on 2019-04-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacted_archiver', '0002_auto_20190328_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redactedarchiverstate',
            name='is_enabled',
        ),
        migrations.AddField(
            model_name='redactedarchiverstate',
            name='is_fetch_missing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redactedarchiverstate',
            name='is_log_follow_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redactedarchiverstate',
            name='is_metadata_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='redactedarchiverstate',
            name='last_meta_tracker_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
