# Generated by Django 3.1.2 on 2020-10-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redacted_archiver', '0003_auto_20190401_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redactedarchiverstate',
            old_name='is_metadata_enabled',
            new_name='is_refresh_metadata_enabled',
        ),
        migrations.RemoveField(
            model_name='redactedarchiverstate',
            name='is_download_enabled',
        ),
    ]
